baseURL: "https://odinsplasmarifle.com"
languageCode: "en-us"
title: OdinsPlasmaRifle
theme: basic-hugo-theme
paginate: 5

author:
  name: OdinsPlasmaRifle
  homepage: https://odinsplasmarifle.com

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

params:
  tagline: A wild coder appears!
  description: A wild coder appears!

  logoImage: /images/logo.jpg
  favicon: /images/favicon.jpg

  githubLink: https://github.com/OdinsPlasmaRifle
  keybaseLink: https://keybase.io/odinsplasmarifle
  linkedInLink: https://www.linkedin.com/in/odinsplasmarifle/
