baseURL: "https://odinsplasmarifle.com"
languageCode: "en-us"
title: "OdinsPlasmaRifle"
theme: basic-hugo-theme
paginate: 5

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

params:
  logoImage: /images/logo.svg
  favicon: /images/favicon.png

  primaryColor: "#606585"
  secondaryColor: "#000000"
