baseURL: "https://odinsplasmarifle.com"
languageCode: "en-us"
title: "OdinsPlasmaRifle"
theme: basic-hugo-theme
paginate: 5

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

params:
  description: Stuff and nonsense.
  about: About me and stuff

  logoImage: /images/logo.jpg
  favicon: /images/favicon.jpg

  primaryColor: "#606585"
  secondaryColor: "#000000"

  githubLink: https://github.com/OdinsPlasmaRifle
  keybaseLink: https://keybase.io/odinsplasmarifle
  linkedInLink: https://www.linkedin.com/in/odinsplasmarifle/
