name = "Basic"
license = "MIT"
licenselink = "https://github.com/OdinsPlasmaRifle/basic-hugo-theme/blob/master/LICENSE"
description = "A theme for a basic blog."
homepage = "https://github.com/OdinsPlasmaRifle/basic-hugo-theme"
tags = ["blog"]
features = []
min_version = "0.102.0"
pygmentsUseClasses = true

[markup]
[markup.highlight]
  style ="dracula"
[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "OdinsPlasmaRifle"
  homepage = "odinsplasmarifle.com"
